In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('../00_DATA_preprocessed/data_tokenized_2classes.csv')
data = data.drop(['Unnamed: 0'], axis = 1)
data

0    1    2    3    4    5    6    7    8    9  ...  72497  72498   
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0  \
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9889  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
9890  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
9891  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
9892  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   
9893  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...    0.0    0.0   

      72499  72500  72501  72502  72503  72504  72505  target  
0       0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
1       0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
2       0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
3       0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
4       0.0    0.0    0.0    0.0    0.0    0.0    0.0       1  
...     ...    ...    ...    ...    ...    ...    ...     ...  
9889    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
9890    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
9891    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
9892    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  
9893    0.0    0.0    0.0    0.0    0.0    0.0    0.0       0  

[9894 rows x 72507 columns]

In [3]:
X_train, X_test, y_train, y_test = train_test_split(data.drop(['target'], axis = 1), data['target'], test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(7915, 72506) (1979, 72506) (7915,) (1979,)


# linear svm

In [4]:
from sklearn.svm import LinearSVC
svm_model_linear = LinearSVC().fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)

accuracy = svm_model_linear.score(X_test, y_test)
print("SVM accuracy: ", accuracy)

SVM accuracy:  0.9772612430520465


In [5]:
from sklearn.metrics import roc_auc_score
score = roc_auc_score(y_test, svm_predictions)
print("ROC: ", score)

ROC:  0.971828107666258


In [6]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, svm_predictions)
cm

array([[1274,   13],
       [  32,  660]], dtype=int64)

In [7]:
svm_model_linear_weighted = LinearSVC(class_weight={0:6410/9894, 1:3484/9894}).fit(X_train, y_train)
svm_predictions_weighted = svm_model_linear_weighted.predict(X_test)

accuracy_weighted = svm_model_linear_weighted.score(X_test, y_test)
print("SVM accuracy (added weights): ", accuracy_weighted)

SVM accuracy (added weights):  0.9580596260737746


In [8]:
score = roc_auc_score(y_test, svm_predictions_weighted)
print("ROC (added weights): ", score)

ROC (added weights):  0.9406969876623057


In [9]:
cm = confusion_matrix(y_test, svm_predictions_weighted)
cm

array([[1285,    2],
       [  81,  611]], dtype=int64)

# Naive Bayes

In [10]:
from sklearn.naive_bayes import MultinomialNB

bayes = MultinomialNB().fit(X_train, y_train)
bayes_predictions = bayes.predict(X_test)

accuracy = bayes.score(X_test, y_test)
print("bayes accuracy: ", accuracy)

bayes accuracy:  0.8676099039919151


In [11]:
score = roc_auc_score(y_test, bayes_predictions)
print("ROC (added weights): ", score)

ROC (added weights):  0.8157042860800086


In [12]:
cm = confusion_matrix(y_test, bayes_predictions)
cm

array([[1272,   15],
       [ 247,  445]], dtype=int64)